field: 923dfd91-51c2-4bd8-b91d-88746e94fcad # Featured Blocks
fieldLayouts:
  4fdcba29-c964-4e70-950c-b0ed71e10f9b:
    tabs:
      -
        elements:
          -
            fieldUid: fd62e3fe-23c7-4e02-b892-132c1d4da8e7 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 46044220-4c91-43c8-a145-52ddd272d71e # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f80a73ba-de41-4c27-af86-c3f04aabb9cd # Bg
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b01be86-7661-4819-89b0-2761a1190d18 # Class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7b01be86-7661-4819-89b0-2761a1190d18: # Class
    columnSuffix: drczjdrw
    contentColumnType: text
    fieldGroup: null
    handle: class
    instructions: 'Extra class to add to markup'
    name: Class
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  46044220-4c91-43c8-a145-52ddd272d71e: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f80a73ba-de41-4c27-af86-c3f04aabb9cd: # Bg
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: bg
    instructions: 'If populated, sets a background color on the block'
    name: Bg
    searchable: false
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  fd62e3fe-23c7-4e02-b892-132c1d4da8e7: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:3ab74c73-4099-4444-85ac-8ee3abd91f6f' # General
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:3ab74c73-4099-4444-85ac-8ee3abd91f6f' # General
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:65e4b53d-2f6c-4765-a073-49728d4efe85' # Featured
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: featureBlock
name: 'Feature Block'
sortOrder: 1
