field: 10f55246-d809-44bd-8498-7f84334a87b4
fieldLayouts:
  163812a3-75c6-42aa-bfb7-0bc5a127edc6:
    tabs:
      -
        fields:
          0902d8a6-a6f3-4a05-8e7d-c84c35e69270:
            required: false
            sortOrder: 3
          45e994b5-951b-4202-93f2-fecfa55c6453:
            required: false
            sortOrder: 2
          b4272c0e-bb8b-49cc-9370-dc4a5e6779fc:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  0902d8a6-a6f3-4a05-8e7d-c84c35e69270:
    contentColumnType: text
    fieldGroup: null
    handle: blockUrl
    instructions: ''
    name: URL
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  45e994b5-951b-4202-93f2-fecfa55c6453:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b4272c0e-bb8b-49cc-9370-dc4a5e6779fc:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c2c921d9-5391-4fad-91a8-0cba08f9e192'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c2c921d9-5391-4fad-91a8-0cba08f9e192'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:c2c921d9-5391-4fad-91a8-0cba08f9e192'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 1
