field: c87b3338-59ec-47e0-b599-8e06a34e3098 # Social Blocks
fieldLayouts:
  e157011b-7587-44a2-b5c7-9a7d75ecdbd6:
    tabs:
      -
        elements:
          -
            fieldUid: e7c04976-9238-4742-af83-3f8d676c9a3f # Header
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c14b803d-ab05-4501-8975-09632862e7d9 # URL
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c14b803d-ab05-4501-8975-09632862e7d9: # URL
    contentColumnType: text
    fieldGroup: null
    handle: socialURL
    instructions: ''
    name: URL
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e7c04976-9238-4742-af83-3f8d676c9a3f: # Header
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: social
name: Social
sortOrder: 1
