field: c87b3338-59ec-47e0-b599-8e06a34e3098
fieldLayouts:
  e157011b-7587-44a2-b5c7-9a7d75ecdbd6:
    tabs:
      -
        fields:
          c14b803d-ab05-4501-8975-09632862e7d9:
            required: '0'
            sortOrder: '2'
          e7c04976-9238-4742-af83-3f8d676c9a3f:
            required: '0'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  c14b803d-ab05-4501-8975-09632862e7d9:
    contentColumnType: text
    fieldGroup: null
    handle: socialURL
    instructions: ''
    name: URL
    searchable: '1'
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e7c04976-9238-4742-af83-3f8d676c9a3f:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: '1'
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: social
name: Social
sortOrder: '1'
