fieldLayouts:
  06a8a299-51a8-412b-8d92-225ebe8a29c7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dc0465c5-db3a-4d88-891f-954fa0db9e0d
            warning: null
            width: 100
          -
            fieldUid: fa9fc1f2-faef-4192-a91e-fdef1db4d7a7 # Body
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82f21785-43bb-4431-8606-60f4c90ad72b
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: f5f17aea-961d-4697-bf41-7d89c3633598
      -
        elements:
          -
            fieldUid: 4b7aee9a-860d-4d7d-8e51-088345eb928f # SEO Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d36cb6-9473-4fd9-b604-e910985442bd
            warning: null
            width: 100
          -
            fieldUid: dd8198bd-9339-4152-911a-2c279336bdd8 # SEO Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae5cf41b-2ee5-4d3c-9f51-2a44ffd40e20
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
        uid: e907d369-1afa-43b7-b5ca-d39abe002f2f
handle: homepage
hasTitleField: true
name: Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
