handle: comics
name: Comics
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00:
    hasUrls: '1'
    template: ''
    uriFormat: '{% if object.level == 1 %}comics/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 4db55afb-502f-4236-aab8-5ad64523d35b
