baseUrl: $DEFAULT_SITE_URL
enabled: true
handle: en_us
hasUrls: true
language: en-US
name: 'Nate Beaty'
primary: true
siteGroup: 7d9814cd-e9f7-4059-82d9-49120c1e1bbc # Nate Beaty (en-US)
sortOrder: 1
