fieldLayouts:
  c4816695-dab6-44ff-a6e9-325ca17d40e0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: sketchbook
hasUrls: true
name: Sketchbook
settings:
  path: '@assetsBasePath/sketchbook'
sortOrder: 6
type: craft\volumes\Local
url: '@assetsBaseUrl/sketchbook'
