contentColumnType: text
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: customCss
instructions: 'Custom CSS for Featured pages'
name: 'Custom CSS'
searchable: '1'
settings:
  charLimit: ''
  columnType: text
  initialRows: '8'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
