columnSuffix: null
contentColumnType: string
handle: featuredBlocks
instructions: ''
name: 'Featured Blocks'
searchable: true
settings:
  entryTypes:
    - b168120a-212b-41d2-b888-5d01268c527e
  maxEntries: ''
  minEntries: ''
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
