contentColumnType: string
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: featuredBlocks
instructions: ''
name: 'Featured Blocks'
searchable: true
settings:
  contentTable: '{{%matrixcontent_featuredblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
