contentColumnType: string
fieldGroup: 055210b5-2633-48be-a17b-a81ecbb643c3
handle: headsploog
instructions: ''
name: Headsploog
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d91247e3-29d1-4ca7-808f-067fe9a54163'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:3ab74c73-4099-4444-85ac-8ee3abd91f6f'
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: ''
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
