columnSuffix: null
handle: images
instructions: null
name: 'Featured Blocks - Feature Block - Images'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:3ab74c73-4099-4444-85ac-8ee3abd91f6f' # General
  defaultUploadLocationSubpath: '{owner.slug}'
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3ab74c73-4099-4444-85ac-8ee3abd91f6f' # General
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  sources:
    - 'volume:65e4b53d-2f6c-4765-a073-49728d4efe85' # Featured
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
