contentColumnType: 'decimal(12,2)'
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: shipping
instructions: 'Use this to override PayPal shipping rates'
name: Shipping
searchable: '1'
settings:
  decimals: '2'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
