contentColumnType: 'decimal(12,2)'
handle: shipping
instructions: 'Use this to override PayPal shipping rates'
name: Shipping
searchable: true
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
