contentColumnType: string
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: sketchbook
instructions: ''
name: Sketchbook
searchable: true
settings:
  contentTable: '{{%matrixcontent_sketchbook}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
