contentColumnType: string
handle: socialBlocks
instructions: ''
name: 'Social Blocks'
searchable: true
settings:
  entryTypes:
    - f3e6c86c-39c3-4aa8-9576-58c353cd9f93
  maxEntries: null
  minEntries: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
