contentColumnType: string
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: tags
instructions: null
name: Tags
searchable: '1'
settings:
  localizeRelations: false
  source: 'taggroup:3b5be951-85be-446f-8974-c6e4cbe515c5'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
