field: d55aaee7-5d0f-4353-a670-b68aed12529f # Site Options
fieldLayouts:
  34acd72a-57c9-484b-8eb1-19e4dfd9b9cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13126522-02f9-44e4-ac47-078e4a42cee4 # Buy Now Enabled
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a736ceb5-9dc0-4921-b4d0-024dbec1720e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d32f02e-8ea4-42b5-b463-af80d535dca2
        userCondition: null
fields:
  13126522-02f9-44e4-ac47-078e4a42cee4: # Buy Now Enabled
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: buyNowEnabled
    instructions: 'Turn on/off buy now buttons in comics section'
    name: 'Buy Now Enabled'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
