defaultPlacement: end
enableVersioning: true
entryTypes:
  - 01cabc32-e6ab-49c1-b259-bc8b98ed911e # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
