defaultPlacement: end
enableVersioning: true
entryTypes:
  - 41732311-3a2e-414b-9d4e-e6d4b3ab95b3 # Comics
handle: comics
maxAuthors: 1
name: Comics
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: comics/_entry
    uriFormat: 'comics/{slug}'
type: channel
