defaultPlacement: end
enableVersioning: true
entryTypes:
  - c539eb18-f49c-416c-a32b-ca32c4fa9fd1 # Featured
handle: featured
maxAuthors: 1
name: Featured
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: featured/_entry
    uriFormat: 'featured/{slug}'
type: channel
