defaultPlacement: end
enableVersioning: true
entryTypes:
  - e98fa039-438e-41bc-b70c-7eaf3c903d61 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
