defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1e2efd00-c7cf-4fd0-9773-f7873bc0f42a # Journal Archives
handle: journalArchives
maxAuthors: 1
name: 'Journal Archives'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: journal/archives
    uriFormat: journal/archives
type: single
