enableVersioning: true
handle: journalArchives
name: 'Journal Archives'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00:
    enabledByDefault: true
    hasUrls: true
    template: journal/archives
    uriFormat: /journal/archives
type: single
