defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9a4b7552-e9c7-4c43-b438-0cfb90308952 # Journal
handle: journal
maxAuthors: 1
name: Journal
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00: # Nate Beaty
    enabledByDefault: true
    hasUrls: true
    template: journal/_entry
    uriFormat: 'journal/{postDate|date("Y")}/{postDate|date("m")}/{slug}'
type: channel
